[package]
name = "malloc_hook"
version = "0.1.0"
edition = "2021"

[lib]


[dependencies]
arrayvec={workspace = true}
jemallocator = { workspace=true}
libc={workspace = true}
memchr = "2.7.4"
tikv-jemalloc-sys = { version = "*", features = ["stats"] }
